- name: Copie fichiers
  hosts: servers
  become: yes
  tasks:
    - name: Copie le projet ansible sur vm-ubuntu-install et lui donne les permissions
      ansible.builtin.copy:
        src: ~/Reprise-DevOps-Project-Ansible
        dest: /home/test
        mode: '777'
    - name: Trouver tous les fichiers et dossiers dans le répertoire de destination
      ansible.builtin.find:
        paths: /home/test/Reprise-DevOps-Project-Ansible
      register: files_to_change

    - name: Changer les permissions sur tous les fichiers et dossiers trouvés
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '777'
      loop: "{{ files_to_change.files }}"