- name: Install docker, jenkins, agent, sonarqube, postgres
  hosts: servers
  become: yes
  #vars_files: 
  #  - secret.yaml
  tasks:
    - name: Installation des dépendences docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Configuration de GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Configuration de repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    
    - name: Installation docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Changer user to test
      ansible.builtin.command: chown -R test /usr/bin/docker
    
    - name: Changer groupe to docker group
      ansible.builtin.command: chgrp -R docker /usr/bin/docker

    - name: Démarrer le service docker
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Création du network jenkins
      ansible.builtin.command: docker network create jenkins

    - name: Installation de jenkins
      ansible.builtin.command: docker run -d --restart on-failure --network jenkins -p 8080:8080 -p 50000:50000 --name jenkins_container jenkins/jenkins:lts

    - name: Installation de sonarqubedb - base des données postgres
      ansible.builtin.command: docker run -d --restart on-failure --name sonarqube-db --network jenkins -e POSTGRES_USER=sonar -e POSTGRES_PASSWORD=sonar postgres:12

    - name: Installation de sonarqube
      ansible.builtin.command: docker run -d --name sonarqube --network jenkins -e SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar -e SONAR_JDBC_USERNAME=sonar -e SONAR_JDBC_PASSWORD=sonar -p 9000:9000 sonarqube:community
  
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted


